[package]
name = "proxmox-router"
version = "2.1.2"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "proxmox API Router and CLI utilities"

exclude.workspace = true

[dependencies]
anyhow.workspace = true
env_logger = { workspace = true, optional = true }
http = { workspace = true, optional = true }
hyper = { workspace = true, features = [ "full" ], optional = true }
nix.workspace = true
percent-encoding.workspace = true
serde_json.workspace = true
serde.workspace = true
unicode-width ="0.1.8"

# cli:
tokio = { workspace = true, features = [], optional = true }
rustyline = { version = "9", optional = true }
libc = { workspace = true, optional = true }

proxmox-lang.workspace = true
proxmox-http-error.workspace = true
proxmox-schema.workspace = true
proxmox-async.workspace = true

[features]
default = [ "cli", "server" ]
cli = [ "dep:env_logger", "dep:libc", "dep:rustyline", "dep:tokio" ]
server = [ "dep:http", "dep:hyper" ]
test-harness = [ "proxmox-schema/test-harness" ]

[patch.crates-io]
rustyline = { path = "https://github.com/jiangcuo/rustyline.git" ,rev = "ae538291a6c1798505b3fd7b0b7a535362656589"}
